version: '3'

volumes:
  allure-docker-service:
    driver: local

services:
  allure-docker-service:
    build:
      context: ../allure-docker-service
      dockerfile: docker/archive/Dockerfile
      args:
        RELEASE: "2.13.2"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: "TRUE"
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
    - ./.data/allure-docker-service/allure-results:/app/allure-results
